### PR TITLE
V3.9

### PR DESCRIPTION
**Pull request by fadytaher**
v3.9

### CODE REVIEW

**Comment by johndpope** [comment]
presumably this is broken?

**Comment by fadytaher** [comment]
@johndpope , I believe it should be working for `user`, `feed` and `video`, let me know if it's not please

**Comment by johndpope** [comment]
the upstream is broken from many months ago - do you seriously have this fixed?

**Comment by fadytaher** [comment]
should be , did you try it and it's not working ?

**Comment by johndpope** [comment]
will keep digging - Screenshot 2023-06-07 at 9 54 38 pm
 **ts-node-script --version
v10.9.1**

**Comment by johndpope** [comment]
the cli - with chmod +x actually downloads video successfully - amazing. (couldn't build the project with above errors - will try on ubuntu)
./bin/cli.js

I'm running 

./bin/cli.js trend dance
⠋ TikTok Scraper StartedError: Can't scrape more posts
    at TikTokScraper.submitScrapingRequest (/Users/johndpope/Documents/gitWorkspace/tikscrap/build/core/TikTok.js:477:23)
Can't scrape more posts
⠦ TikTok Scraper Started

no errors yet


UPDATE
Looking at one your updates you changed api end point from api -> share but only for user. does it need too for trend I wonder?


         case 'user':
                return `${this.mainHost}api/post/item_list/`;
                // return `${this.mainHost}api/post/item_list/`;
                return `${this.mainHost}share/item/list`;
            case 'trend':
                return `${this.mainHost}api/recommend/item_list/`;
            case 'hashtag':

**Comment by fadytaher** [comment]
@johndpope , try the nodejs api if possible, I focused on that as I wasn't using CLI, can't promise I can have a fix for CLI right now

**Comment by johndpope** [comment]
I bumped the typescript to         "typescript": "^4.6.3" and compiled - had to do some hackery to make the (error) -> (error:any)+ (err:any) - then it all compiled fine. it doesn't seem like the hashtag stuff is working. I attempted to switch in share/ in the trend code above 
return `${this.mainHost}api/recommend/item_list/`; -> return `${this.mainHost}share/recommend/item_list/`;

that didn't work but found python code that's working.

**Pull request merged**
